required = ["k8s.io/code-generator/cmd/client-gen"]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.2"


